### PR TITLE
Properly handle inaccessible or un-modifiable exception attributes

### LINKED ISSUE #57: AttributeError: characters_written
I am having an issue where the messages are not being scrubbed. Instead the scrub_message() function is crashing. I am using confidential-ml-utils==0.7.2 and python 3.7.9. I am running this in ubuntu 18.04 in WSL.

I am running a modified version of the front page example but introducing a file not found error.

```
from confidential_ml_utils import DataCategory, enable_confidential_logging, prefix_stack_trace
import logging


@prefix_stack_trace(allow_list=["FileNotFoundError", "SystemExit", "TypeError"])
def main():
    enable_confidential_logging()

    log = logging.getLogger(__name__)
    log.info("Hi there", category=DataCategory.PUBLIC)

    infile = open('this file does not exist')

if __name__ == "__main__":
    main()
````

I get this error:

```
SystemLog:INFO:__main__:Hi there
Traceback (most recent call last):
  File "break_scrubber.py", line 15, in <module>
    main()
  File "/home/clthorre/anaconda3/envs/comtriage/lib/python3.7/site-packages/confidential_ml_utils/exceptions.py", line 287, in wrapper
    caught_err,
  File "/home/clthorre/anaconda3/envs/comtriage/lib/python3.7/site-packages/confidential_ml_utils/exceptions.py", line 220, in print_prefixed_stack_trace_and_raise
    scrubbed_err = scrub_exception(err, scrub_message, prefix, keep_message, allow_list)
  File "/home/clthorre/anaconda3/envs/comtriage/lib/python3.7/site-packages/confidential_ml_utils/exceptions.py", line 166, in scrub_exception
    value = getattr(exception, attr)
AttributeError: characters_written
```

With a little further investigation, I get the expected results for some other types of errors. 
`ZeroDivisionError: SystemLog:**Exception message scrubbed**`
`NameError: SystemLog:**Exception message scrubbed**`
FileNotFoundError is the only one I've seen so far the doesn't work.

### PR DESCRIPTION
**Pull request by dkmiller**
Properly handle the different cases of "un-readable attribute" and "un-scrubbable attribute" that an exception may have. If unable to **read** an attribute value, don't attempt to scrub it and move on. If unable to **change** an attribute value, replace the current exception with a public runtime error, to ensure no private data is leaked.

Closes #57 .

After this change, a file like:

```python
from confidential_ml_utils import DataCategory, enable_confidential_logging, prefix_stack_trace
import logging


@prefix_stack_trace(allow_list=["FileNotFoundError", "SystemExit", "TypeError"])
def main():
    enable_confidential_logging()

    log = logging.getLogger(__name__)
    log.info("Hi there", category=DataCategory.PUBLIC)

    infile = open('this file does not exist')

if __name__ == "__main__":
    main()
```

will result in scrubbed logs like:

> SystemLog:INFO:__main__:Hi there
SystemLog: Traceback (most recent call last):
SystemLog:   File "../docs/logging/hello-world.py", line 12, in main
SystemLog:     infile = open('this file does not exist')
SystemLog: FileNotFoundError: [Errno 2] SystemLog:No such file or directory: 'SystemLog:this file does not exist' -> None

### CODE REVIEW

**Review by aminsaied — APPROVED** [review]

**Comment by clthorre** [comment]
What will the output look like if there is a FileNotFoundError but FileNotFoundError is not in the allow_list?

**Comment by dkmiller** [comment]
@clthorre if "file not found error" is not in the allow list, the scrubbed logs look like:

> SystemLog:INFO:__main__:Hi there
SystemLog: Traceback (most recent call last):
SystemLog:   File "docs/logging/hello-world.py", line 12, in main
SystemLog:     infile = open('this file does not exist')
SystemLog: FileNotFoundError: [Errno None] SystemLog:**Exception message scrubbed**: 'SystemLog:**Exception message scrubbed**' -> None

**Comment by clthorre** [comment]
@dkmiller Thanks! looks good to me.

**Review by danrsc — COMMENTED** [review]
LGTM

**Review by fuhuifang — COMMENTED** [review]
reviewed changes

**Pull request merged**
